global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "groundtruth"
    static_configs:
      - targets: ["server:3001"]
    metrics_path: /metrics
    scrape_interval: 30s
